apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: merchant
  name: merchant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: merchant
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/cicdnetwork: "true"
        io.kompose.service: merchant
    spec:
      containers:
        - image: josiokoko/merchant:latest
          name: merchant
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
